import { FormStep } from "@/interfaces/form";
import { FieldType } from "@/interfaces/section";

export const defaultValuesLegalEntity = {
  application_type: "legal_entity",
  pa_id: "",
  clr_cp_id: "",
  clr_hunter_id: "",
  clr_requested_loc: 0,
  Show_cupo: "",
  clr_first_name: "",
  clr_doc_number: "",
  clr_city: "",
  clr_bus_address: "",
  clr_email: "",
  clr_pj_year_of_establishment: "",
  clr_pj_legal_rep_name: "",
  clr_pj_legal_rep_last_name: "",
  clr_pj_legal_rep_doc_type: "",
  clr_pj_legal_rep_doc_number: "",
  clr_phone: "",
  direccion_del_representante_legal: "",
  clr_bus_name: "",
  clr_bus_type: "",
  clr_bus_seniority: "",
  clr_bus_num_locations: "",
  clr_bus_num_employees: "",
  clr_bus_flagship_m2: "",
  clr_has_rent: "",
  clr_rent: "",
  show_assets: "",
  clr_bus_total_assets: "",
  show_income: "",
  clr_bus_monthly_income: "",
  show_exp: "",
  clr_bus_monthly_expenses: "",
  alias: "",
  clr_bus_is_client: "",
  show_mothly_purchases: "",
  clr_bus_monthly_purchases: "",
  show_mothly_purchases_copy: "",
  clr_bus_current_purchases: "",
  clr_pj_shareholders_repeater: [
    {
      shareholder_name: "",
      shareholder_last_name: "",
      shareholder_doc_type: "",
      shareholder_doc_number: "",
      shareholder_percent: "",
      beneficial_owners: "",
    },
  ],
  clr_pj_eeff: {
    id: "",
    url: "",
  },
  clr_sales_rep_knowledge_time: "",
  clr_sales_rep_confidence: "",
  clr_sales_rep_suggested_limit: "",
  autoriz: "",
  __form_id: "",
  __refer: "",
  __is_ajax: "",
};

export const legalEntityFormFields: FormStep[] = [
  {
    step: 1,
    sections: [
      {
        section: "Representante de Ventas",
        columns: 1,
        fields: [
          {
            name: "clr_hunter_id",
            label: "Representante de Ventas",
            typefield: FieldType.Select,
            placeholder: "Buscar",
            optionsName: "salesRepresentatives",
            rules: { required: "El representante de ventas es requerido" },
          },
        ],
      },
      {
        section: "Empresa",
        columns: 2,
        fields: [
          {
            name: "clr_first_name",
            label: "Razón Social",
            typefield: FieldType.Input,
            type: "text",
            placeholder: "Ejemplo: Company S.A.S",
            rules: { required: "La Razón Social es requerida" },
          },
          {
            name: "clr_doc_number",
            label: "NIT",
            typefield: FieldType.Input,
            type: "text",
            placeholder: "Sin dígito de verificación",
            rules: { required: "El NIT es requerido" },
          },
          {
            name: "clr_city",
            label: "Ciudad",
            typefield: FieldType.Select,
            placeholder: "Buscar",
            optionsName: "cities",
            rules: { required: "La ciudad es requerida" },
          },
          {
            name: "clr_bus_address",
            label: "Dirección principal de la empresa",
            typefield: FieldType.Input,
            type: "text",
            placeholder: "Ejemplo: Calle 123 #456",
            rules: { required: "La dirección es requerida" },
          },
          {
            name: "clr_email",
            label: "Correo electrónico de contacto",
            typefield: FieldType.Input,
            type: "email",
            rules: {
              required: "El correo es requerido",
              pattern: {
                value: /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i,
                message: "Correo electrónico inválido",
              },
            },
          },
          {
            name: "clr_pj_year_of_establishment",
            label: "Año de constitución",
            typefield: FieldType.Input,
            type: "number",
            placeholder: "YYYY",
            rules: { required: "El año de constitución es requerido" },
          },
        ],
      },
      {
        section: "Solicitud",
        columns: 1,
        fields: [
          {
            name: "clr_requested_loc",
            label: "¿Qué cupo de línea de crédito necesitas para tu negocio?",
            typefield: FieldType.InputNumber,
            integerOnly: true,
            useGrouping: true,
            numberFormatLocale: "es-CO",
            prefix: "$",
            rules: { required: "El monto solicitado es requerido" },
          },
        ],
      },
    ],
  },
  {
    step: 2,
    sections: [
      {
        section: "Datos del representante legal",
        columns: 2,
        fields: [
          {
            name: "clr_pj_legal_rep_name",
            label: "Nombres del representante legal",
            typefield: FieldType.Input,
            type: "text",
            rules: { required: "Nombres requeridos" },
          },
          {
            name: "clr_pj_legal_rep_last_name",
            label: "Apellidos del representante legal",
            typefield: FieldType.Input,
            type: "text",
            rules: { required: "Apellidos requeridos" },
          },
          {
            name: "clr_pj_legal_rep_doc_type",
            label: "Tipo de documento del representante legal",
            typefield: FieldType.Select,
            optionsName: "documentTypes",
            rules: { required: "Tipo de documento requerido" },
          },
          {
            name: "clr_pj_legal_rep_doc_number",
            label: "Número de documento del representante legal",
            typefield: FieldType.Input,
            type: "text",
            rules: { required: "Número de documento requerido" },
          },
          {
            name: "clr_phone",
            label: "Número de celular del representante legal",
            typefield: FieldType.Input,
            type: "text",
            placeholder: "Sin indicativo de país",
            rules: { required: "Celular requerido" },
          },
          {
            name: "direccion_del_representante_legal",
            label: "Dirección del representante legal",
            typefield: FieldType.Input,
            type: "text",
            rules: { required: "Dirección requerida" },
          },
        ],
      },
    ],
  },
  {
    step: 3,
    sections: [
      {
        section: "Datos del Negocio",
        columns: 2,
        fields: [
          {
            name: "clr_bus_name",
            label: "Nombre comercial del negocio",
            typefield: FieldType.Input,
            type: "text",
            rules: { required: "Nombre comercial requerido" },
          },
          {
            name: "clr_bus_type",
            label: "Tipo de negocio",
            typefield: FieldType.SearchSelect,
            optionsName: "businessTypes",
            placeholder: "Buscar",
            rules: { required: "Tipo de negocio requerido" },
          },
          {
            name: "pa_id",
            label: "Categoría de Negocio",
            typefield: FieldType.Select,
            optionsName: "partnerCategories",
            placeholder: "Buscar",
            rules: { required: "Categoría de negocio requerida" },
          },
          {
            name: "clr_bus_num_locations",
            label: "Cantidad de locales",
            typefield: FieldType.InputNumber,
            type: "number",
            useGrouping: false,
            rules: { required: "Cantidad de locales requerida" },
          },
          {
            name: "clr_bus_num_employees",
            label: "Número de empleados",
            typefield: FieldType.InputNumber,
            type: "number",
            useGrouping: false,
            rules: { required: "Número de empleados requerido" },
          },
          {
            name: "clr_bus_seniority",
            label: "Antigüedad",
            typefield: FieldType.Select,
            optionsName: "businessSeniority",
            rules: { required: "Antigüedad requerida" },
          },
          {
            name: "clr_bus_flagship_m2",
            label: "¿Cuál es el tamaño de tu local principal? (m²)",
            typefield: FieldType.InputNumber,
            type: "number",
            useGrouping: false,
            suffix: "m²",
            rules: { required: "Tamaño requerido" },
          },
          {
            name: "clr_has_rent",
            label: "¿Arrienda el(los) local(es) donde opera su negocio?",
            typefield: FieldType.Select,
            options: [
              { label: "Sí", value: "Si" },
              { label: "No", value: "No" },
            ],
            rules: { required: "Requerido" },
          },
          {
            name: "clr_rent",
            label: "Valor mensual total de arriendos",
            typefield: FieldType.InputNumber,
            integerOnly: true,
            useGrouping: true,
            numberFormatLocale: "es-CO",
            prefix: "$",
            dependency: "clr_has_rent",
            dependencyValue: "Si",
            rules: { required: "Monto requerido" },
          },
        ],
      },
      {
        section: "Información Financiera",
        columns: 2,
        fields: [
          {
            name: "clr_bus_total_assets",
            label: "Total de activos del negocio",
            typefield: FieldType.InputNumber,
            integerOnly: true,
            useGrouping: true,
            numberFormatLocale: "es-CO",
            prefix: "$",
            rules: { required: "Total de activos requerido" },
          },
          {
            name: "clr_bus_monthly_income",
            label: "Ventas mensuales",
            typefield: FieldType.InputNumber,
            integerOnly: true,
            useGrouping: true,
            numberFormatLocale: "es-CO",
            prefix: "$",
            rules: { required: "Ventas mensuales requeridas" },
          },
          {
            name: "clr_bus_monthly_expenses",
            label: "Gastos mensuales en inventario",
            typefield: FieldType.InputNumber,
            integerOnly: true,
            useGrouping: true,
            numberFormatLocale: "es-CO",
            prefix: "$",
            rules: { required: "Gastos mensuales requeridos" },
          },
        ],
      },
      {
        section: "Relación con el Cliente",
        columns: 1,
        fields: [
          {
            name: "clr_bus_is_client",
            label: "¿Es cliente actual con ustedes?",
            typefield: FieldType.Select,
            options: [
              { label: "Sí", value: "Si" },
              { label: "No", value: "No" },
            ],
            rules: { required: "Requerido" },
          },
          {
            name: "clr_bus_monthly_purchases",
            label: "¿Cuánto suele comprar mensualmente?",
            typefield: FieldType.InputNumber,
            integerOnly: true,
            useGrouping: true,
            numberFormatLocale: "es-CO",
            prefix: "$",
            dependency: "clr_bus_is_client",
            dependencyValue: "Si",
            rules: { required: "Monto requerido" },
          },
        ],
      },
    ],
  },
  {
    step: 4,
    sections: [
      {
        section: "Datos de los accionistas",
        columns: 1,
        fields: [
          {
            name: "clr_pj_shareholders_repeater.0.shareholder_name",
            label: "Nombres",
            typefield: FieldType.Input,
            type: "text",
            rules: { required: "Nombres requeridos" },
          },
          {
            name: "clr_pj_shareholders_repeater.0.shareholder_last_name",
            label: "Apellidos",
            typefield: FieldType.Input,
            type: "text",
            rules: { required: "Apellidos requeridos" },
          },
          {
            name: "clr_pj_shareholders_repeater.0.shareholder_doc_type",
            label: "Tipo documento",
            typefield: FieldType.Select,
            optionsName: "documentTypes",
            rules: { required: "Tipo de documento requerido" },
          },
          {
            name: "clr_pj_shareholders_repeater.0.shareholder_doc_number",
            label: "Número documento",
            typefield: FieldType.Input,
            type: "text",
            rules: { required: "Número de documento requerido" },
          },
          {
            name: "clr_pj_shareholders_repeater.0.shareholder_percent",
            label: "Participación %",
            typefield: FieldType.Input,
            type: "text",
            rules: { required: "Participación requerida" },
          },
        ],
      },
    ],
  },
  {
    step: 5,
    dependency: "application_type",
    dependencyValue: "sales_representative",
    sections: [
      {
        section: "Opinión Representante de Ventas",
        columns: 1,
        fields: [
          {
            name: "clr_sales_rep_knowledge_time",
            label: "¿Hace cuánto conoces al cliente?",
            typefield: FieldType.Select,
            options: [
              { label: "Lo acabo de conocer", value: "Lo acabo de conocer" },
              { label: "Menos de 3 meses", value: "Menos de 3 meses" },
              { label: "Entre 3 y 6 meses", value: "Entre 3 y 6 meses" },
              { label: "Más de 6 meses", value: "Más de 6 meses" },
            ],
            rules: { required: "Requerido" },
          },
          {
            name: "clr_sales_rep_confidence",
            label: "En una escala del 1 al 10, ¿qué tan seguro/a te sientes de prestarle al cliente?",
            typefield: FieldType.InputNumber,
            useGrouping: false,
            suffix: "puntos",
            rules: {
              required: "Requerido",
              min: { value: 1, message: "Mínimo 1" },
              max: { value: 10, message: "Máximo 10" },
            },
          },
          {
            name: "clr_sales_rep_suggested_limit",
            label: "Con base en tu conocimiento del cliente y su negocio, ¿cuál sería el cupo de crédito apropiado para él?",
            typefield: FieldType.InputNumber,
            integerOnly: true,
            useGrouping: true,
            numberFormatLocale: "es-CO",
            prefix: "$",
            rules: { required: "Monto sugerido requerido" },
          },
        ],
      },
    ],
  },
];
